In [ ]:
import $ivy.`org.apache.spark::spark-sql:2.4.5` 
import $ivy.`sh.almond::almond-spark:0.4.0`

import org.apache.spark.sql.{NotebookSparkSession, SparkSession}
import org.apache.spark.sql.{functions => func, _}
import org.apache.spark.sql.types._

val spark = NotebookSparkSession
      .builder()
      .config("spark.sql.join.preferSortMergeJoin", false)
      .config("spark.sql.shuffle.partitions", 64)
      .master("local[4]")
      .getOrCreate()

import spark.implicits._

import org.slf4j.LoggerFactory
import org.apache.log4j.{Level, Logger}

Logger.getRootLogger().setLevel(Level.ERROR)

In [ ]:
import $ivy.`org.plotly-scala::plotly-almond:0.7.0`
import plotly._, plotly.element._, plotly.layout._, plotly.Almond._

repl.pprinter() = repl.pprinter().copy(defaultHeight = 3)

In [ ]:
val data= spark.read.parquet("../data/monthParquet/")

val results = data
    .withColumn("ta_max", func.split($"ta_max", "\\(")(0).cast(IntegerType))
    .groupBy($"fecha")
    .agg(func.avg($"ta_max").alias("ta_max"))
    .withColumn("año", func.year($"fecha"))
    .withColumn("mes", func.month($"fecha"))
    .orderBy("año", "mes")
    .repartition(4)

In [ ]:
def seqYear(year : Int): Seq[Double] = {
    results.filter($"año" === year).map(row => row.getDouble(1)).collect().toSeq
}

val SeqMonths = results.filter($"año" === 2010).map(row => row.getInt(3)).collect().toSeq

val Seq2010 = seqYear(2010)
val Seq2011 = seqYear(2011)
val Seq2012 = seqYear(2012)
val Seq2013 = seqYear(2013)
val Seq2014 = seqYear(2014)
val Seq2015 = seqYear(2015)
val Seq2016 = seqYear(2016)
val Seq2017 = seqYear(2017)
val Seq2018 = seqYear(2018)
val Seq2019 = seqYear(2019)
val Seq2020 = seqYear(2020)
val Seq2021 = seqYear(2021)
val Seq2022 = seqYear(2022)

In [ ]:
val year2010= Scatter(
  SeqMonths,
  Seq2010,
  name = "año 2010"
)

val year2011 = Scatter(
  SeqMonths,
  Seq2011,
  name = "año 2011"
)

val year2012 = Scatter(
  SeqMonths,
  Seq2012,
  name = "año 2012"
)

val year2013 = Scatter(
  SeqMonths,
  Seq2013,
  name = "año 2013"
)

val year2014 = Scatter(
  SeqMonths,
  Seq2014,
  name = "año 2014"
)

val year2015 = Scatter(
  SeqMonths,
  Seq2015,
  name = "año 2015"
)

val year2016 = Scatter(
  SeqMonths,
  Seq2016,
  name = "año 2016"
)

val year2017 = Scatter(
  SeqMonths,
  Seq2017,
  name = "año 2017"
)

val year2018 = Scatter(
  SeqMonths,
  Seq2018,
  name = "año 2018"
)

val year2019 = Scatter(
  SeqMonths,
  Seq2019,
  name = "año 2019"
)

val year2020 = Scatter(
  SeqMonths,
  Seq2020,
  name = "año 2020"
)

val year2021 = Scatter(
  SeqMonths,
  Seq2021,
  name = "año 2021"
)

val year2022 = Scatter(
  SeqMonths,
  Seq2022,
  name = "año 2022"
)



val dataToPlot = Seq(year2010, year2011, year2012, year2013, year2014, year2015, year2016, 
                     year2017, year2018, year2019, year2020, year2021, year2022)

plot(dataToPlot)